### ISSUE TITLE
Show how to add argparse in a Cargo.toml

### ISSUE THREAD

**Issue by lambdaburrito** [tailhook/rust-argparse#15]
It would be ideal to show how to add argparse as a dependency in `Cargo.toml` in the readme.md.

People new to Rust won't know how to add it as a dependency,

**Comment by tailhook** [comment]
Yes. Do you want to contribute changes to README.rst?

**Comment by lambdaburrito** [comment]
Yeah, just about to send a pull request your way :)

**Comment by tailhook** [comment]
Merged in #16
