### ISSUE TITLE
No way to do required arguments(?)

### ISSUE THREAD

**Issue by lahwran** [tailhook/rust-argparse#19]
That I could find, anyway. I searched the repository for "require" and found nothing.

**Comment by tailhook** [comment]
There is a `required()` method. I've added docs to README. Please, close the issue when you think that documentation is clear enough.

**Comment by lahwran** [comment]
It'd be super cool to have rustdoc documentation, but cool, I found it.

**Comment by tailhook** [comment]
I don't like rustdoc because it has documentation embedded in source code. And documentation should have much different structure than code. But I may be happy if anyone wants to contribute rustdoc documentation.
