### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zetok** [tailhook/rust-argparse#22]
As it is currently, rust-argparse is a proprietary code, since that's what missing license means.
I think that it's not the desired state of things?

If you are not sure which one to pick, there's https://tldrlegal.com/

Depending on what you want, you most likely may want to pick one of "main" licenses:
* [GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29) (if you want my biased opinion, this is The One :3 )
* [MIT](https://tldrlegal.com/license/mit-license)
* [BSD](https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29)
* [LGPL-3](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-%28lgpl-3%29)

**Comment by tailhook** [comment]
Hi. rust-argparse has MIT license. I will add a license file soon.

**Comment by tailhook** [comment]
Done. By the way, license kind was always specified in `Cargo.toml`
