### ISSUE TITLE
Update on crates.io?

### ISSUE THREAD

**Issue by nicohman** [tailhook/rust-argparse#46]
Hey, I'm using this library for a cli app, but I need to use PushConst with a type that implements Clone, but not Copy. #4c20997 removes this requirement, but that hasn't been published to crates.io yet. Would you mind publishing the latest version on crates.io? Thanks!

**Comment by tailhook** [comment]
Sure, published 0.2.2 (still waiting for travis).

By the way, any specific reason you're using rust-argparse? I think StructOpt is more popular nowadays.

**Comment by nicohman** [comment]
None in particular really. Just decided to use it.
