### ISSUE TITLE
List possible subcommands for one argument

### ISSUE THREAD

**Issue by nifker** [tailhook/rust-argparse#48]
Wouldnt it be better if theres the possibility to list all the subcommands which can be used as "COMMAND" and each of them would have an own description? - instead of "command Command to run (either "play" or "record")".  
  
Like this:
```
command short summing up description
  play description for "play"
  record description for "record"
```

**Comment by tailhook** [comment]
Unfortunately, there is no "subcommand" thing in rust-argparse. This project is in "maintenance only no new features mode" so it's unlikely that they be added anytime. And it's better to use [structopt](https://crates.io/crates/structopt) or [clap](https://crates.io/crates/clap) nowadays.
